### ISSUE TITLE
VirtualTreeView.pas does not compile for Win64

### ISSUE THREAD

**Issue by DanielWolf** [TurboPack/VirtualTreeView#1]
Create a new VCL-application, select Win64 as target-platform.
Drop a TVirtualStringTree on the form and compile.

Error-Messages:
[dcc64 Error] VirtualTrees.pas(20888): E2089 Invalid typecast
[dcc64 Error] VirtualTrees.pas(20891): E2089 Invalid typecast
[dcc64 Error] VirtualTrees.pas(20893): E2089 Invalid typecast
[dcc64 Fatal Error] Unit3.pas(7): F2063 Could not compile used unit 'VirtualTrees.pas'

In the lines mentioned above, there is a typecast from SmallPoint to "NativeInt", the original source contains a typecast to LongInt - this still works.

**Comment by romankassebaum** [comment]
Fixed.

**Comment by DanielWolf** [comment]
Thank you for your support.

**Comment by DanielWolf** [comment]
How is this change promoted to GetIt?
I did now a fresh install of TVirtualTreeView using XE8 and the change is not there.
It still does not compile for Win64.

**Comment by marcocantu** [comment]
## It is a manual process, should take a day or two.

Marco Cantù
RAD Studio Product Manager
Embarcadero Technologies

**Comment by romankassebaum** [comment]
"How is this change promoted to GetIt?"

EMBT uses its own copy of the repo. That's why I yesterday sent an email to Marco and asked him to get the latest sources. I will send him another message.

**Comment by DanielWolf** [comment]
Ah okay, this is something I did not know.
Thank you. :-)
